### ISSUE TITLE
driller/run.py dies with exception: redis.exceptions.ResponseError: invalid DB index

### ISSUE THREAD

**Issue by singlethink** [shellphish/driller#1]
Running driller via driller/run.py, it dies with an "invalid DB index" response from Redis when attempting to subscribe to the `crashes` channel:

```
driller@4f039bfa4c56:~$ driller/run.py /binaries
INFO    | 2016-09-06 18:57:42,921 | driller | 2 binaries found
INFO    | 2016-09-06 18:57:42,921 | driller | 2 binaries found
INFO    | 2016-09-06 18:57:42,921 | driller | going to work on 2
INFO    | 2016-09-06 18:57:42,951 | driller | listening for crashes..
Traceback (most recent call last):
  File "driller/run.py", line 87, in <module>
    sys.exit(main(sys.argv))
  File "driller/run.py", line 84, in main
    start(binary_dir)
  File "driller/run.py", line 68, in start
    p.subscribe("crashes")
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2229, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2161, in execute_command
    self._execute(connection, connection.send_command, *args)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2165, in _execute
    return command(*args)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 446, in connect
    self.on_connect()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 520, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: invalid DB index
```

Removing the `db=` argument to [`redis.Redis()`](https://github.com/shellphish/driller/blob/master/run.py#L65) appears to fix the problem.

This issue was observed on Debian 8 (jessie), with Python 2.7.12 and redis-py 2.10.5.

**Comment by salls** [comment]
I think the right thing is to set config.REDIS_DB = 0. It depends what your setup is, but 0 is the default.

**Comment by ronakdborad** [comment]
Can you please provide the sample configuration file for config.py
