### ISSUE TITLE
Attribute error due to lifter

### ISSUE THREAD

**Issue by ronakdborad** [shellphish/driller#11]
Hi,

I am using driller under virtualenvironment. I have done installation of angr, tracer and other dependencies.

While using it my script stops with error. It is as below:
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    new_inputs = d.drill()
  File "/home/rborad/driller/local/lib/python2.7/site-packages/driller/driller.py", line 103, in drill
    list(self._drill_input())
  File "/home/rborad/driller/local/lib/python2.7/site-packages/driller/driller.py", line 187, in _drill_input
    branches = t.next_branch()
  File "/home/rborad/driller/local/lib/python2.7/site-packages/tracer/tracer.py", line 322, in next_branch
    except angr.lifter.AngrMemoryError:
AttributeError: 'module' object has no attribute 'lifter'

Can anyone please help me with it.

Thanks.

**Comment by salls** [comment]
That was fixed in this commit:
https://github.com/angr/tracer/commit/8690a486409a7d8eedcaac7955a8e5b695ff0eb7
Make sure to checkout the latest version of tracer and driller and update them whenever you update angr.

**Comment by ronakdborad** [comment]
Thanks.
