### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ExitStack'

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [shellphish/driller#79]
While trying to run driller with shellphuzz I got this error : 

AttributeError: 'module' object has no attribute 'ExitStack'

The full output of the Error is : 

[*] Waiting for fuzzer completion (timeout: None, first_crash: False).
WARNING | 2019-10-23 21:10:17,101 | angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups.
WARNING | 2019-10-23 21:10:17,140 | tracer.tracer | Tracer package is deprecated, please use Tracer exploration technique instead.
WARNING | 2019-10-23 21:10:18,124 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
Traceback (most recent call last):
  File "/tmp/pip-install-HMRpMz/driller/driller/local_callback.py", line 104, in <module>
    for new_input in d.drill_generator():
  File "/usr/local/lib/python2.7/dist-packages/driller/driller.py", line 129, in drill_generator
    for i in self._drill_input():
  File "/usr/local/lib/python2.7/dist-packages/driller/driller.py", line 139, in _drill_input
    t = tracer.Tracer(self.binary, self.input, hooks=self._hooks, argv=self.argv)
  File "/opt/AFL/src/tracer/tracer/tracer.py", line 60, in __init__
    self.r = QEMURunner(binary=binary, input=input, seed=seed, argv=argv, project=project)
  File "/opt/AFL/src/tracer/tracer/qemu_runner.py", line 168, in __init__
    self._run()
  File "/opt/AFL/src/tracer/tracer/qemu_runner.py", line 383, in _run
    core_target=core_target if self._record_core else None
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/AFL/src/tracer/tracer/qemu_runner.py", line 265, in _exec_func
    with self._mk_tmpdir() as tmpdir, self._tmpfile(dir="/dev/shm/", prefix="tracer-log-") as trace_filename, self._tmpfile(dir="/dev/shm/", prefix="tracer-magic-") as magic_filename, contextlib.ExitStack() as exit_stack:
AttributeError: 'module' object has no attribute 'ExitStack'
('', None)

**Comment by rhelmot** [comment]
This means you are using a too-old version of python. You must use python 3.5 or newer. Python 2 is about to end its life as supported software. You should really never use it.

**Comment by KittyTechnoProgrammer** [comment]
Thx didn't know it was python3. Been using python2
