### ISSUE TITLE
Running CGC binaries with Driller

### ISSUE THREAD

**Issue by rklm20** [shellphish/driller#86]
Hello, I have been trying to run driller in a docker container and cannot seem to get it to work. The error I obtain -

shellphuzz -d 2 -w workdir/shellphuzz/ -C --length-extension 4 ./CADET_00001 
[*] Drilling...
[*] Creating fuzzer...
ERROR   | 2020-09-03 16:33:21,002 | fuzzer.fuzzer | AFL Warning: We probably want the fork() children to run first
execute 'echo 1 | sudo tee /proc/sys/kernel/sched_child_runs_first'

Traceback (most recent call last):
  File "/home/angr/.virtualenvs/angr/bin/shellphuzz", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/angr/angr-dev/fuzzer/shellphuzz", line 87, in <module>
    memory=args.memory, seeds=seeds, timeout=args.run_timeout,
  File "/home/angr/angr-dev/fuzzer/fuzzer/fuzzer.py", line 99, in __init__
    Fuzzer._perform_env_checks()
  File "/home/angr/angr-dev/fuzzer/fuzzer/fuzzer.py", line 599, in _perform_env_checks
    raise InstallError(err)
fuzzer.fuzzer.InstallError: AFL Warning: We probably want the fork() children to run first
execute 'echo 1 | sudo tee /proc/sys/kernel/sched_child_runs_first'

Exception ignored in: <bound method Fuzzer.__del__ of <fuzzer.fuzzer.Fuzzer object at 0x7f6062895e10>>
Traceback (most recent call last):
  File "/home/angr/angr-dev/fuzzer/fuzzer/fuzzer.py", line 665, in __del__
    self.kill()
  File "/home/angr/angr-dev/fuzzer/fuzzer/fuzzer.py", line 266, in kill
    for p in self.procs:
AttributeError: 'Fuzzer' object has no attribute 'procs'

Running 'echo 1 | sudo tee /proc/sys/kernel/sched_child_runs_first' tells me the file system is read_only.

Any advice would be much appreciated.

**Comment by twizmwazin** [comment]
I believe you need to either run the container as privileged, or you can run it on the host.
