### ISSUE TITLE
Driller on CGC programs

### ISSUE THREAD

**Issue by ymgh96** [shellphish/driller#87]
Hi, I want to test CGC programs with driller. so I call AFL separately and then call driller simultaneous (according to run_driller.py from [here](https://blog.grimm-co.com/2020/05/guided-fuzzing-with-driller.html)).
But I get the below exception:
```
Drilling input: b'init'
Traceback (most recent call last):
  File "run_driller.py", line 109, in <module>
    main()
  File "run_driller.py", line 83, in main
    for _, new_input in Driller(binary, seed, z_address_score, fuzzer_bitmap).drill_generator():
  File "/home/ymgh96/driller/venv/lib/python3.6/site-packages/driller/driller_main.py", line 106, in drill_generator
    for i in self._drill_input():
  File "/home/ymgh96/driller/venv/lib/python3.6/site-packages/driller/driller_main.py", line 167, in _drill_input
    simgr.step()
  File "/home/ymgh96/driller/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/ymgh96/driller/venv/lib/python3.6/site-packages/angr/exploration_techniques/driller_core.py", line 39, in step
    simgr.step(stash=stash, **kwargs)
  File "/home/ymgh96/driller/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/ymgh96/driller/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 227, in step
    return simgr.step(stash=stash, **kwargs)
  File "/home/ymgh96/driller/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/home/ymgh96/driller/venv/lib/python3.6/site-packages/angr/sim_manager.py", line 347, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/home/ymgh96/driller/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/ymgh96/driller/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 288, in step_state
    succ = self._pick_correct_successor(succs)
  File "/home/ymgh96/driller/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 364, in _pick_correct_successor
    raise Exception("No states followed the trace?")
Exception: No states followed the trace?
```
I should mention that my OS is Ubuntu 18.04. So I can't compile CGC source code myself and I use compiled binaries from [here](https://github.com/trailofbits/cb-multios).
Where is the problem?

**Comment by rhelmot** [comment]
The trail of bits re-compilations of the cgc binaries are known to be problematic in angr. there are sooooooo many issues that pop up when you try to trace linux binaries. I can look into this particular case, but there will definitely be more pitfalls coming. Can you post reproduction instructions? If possible, can you minimize the testcase to just involve the tracer and not driller?

**Comment by ymgh96** [comment]
> The trail of bits re-compilations of the cgc binaries are known to be problematic in angr. there are sooooooo many issues that pop up when you try to trace linux binaries. I can look into this particular case, but there will definitely be more pitfalls coming. Can you post reproduction instructions? If possible, can you minimize the testcase to just involve the tracer and not driller?

You are right. There are so problems with these binaries. So I use from the main CGC binaries like binaries have been published [here](https://github.com/zardus/cgc-bins).
Thank you
