### ISSUE TITLE
AFL Warning: We probably want the fork() children to run first

### ISSUE THREAD

**Issue by xiaozhouqi** [shellphish/driller#94]
1、Problem description
Traceback (most recent call last):
  File "/home/angr/.virtualenvs/angr/bin/shellphuzz", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/angr/angr-dev/fuzzer/shellphuzz", line 87, in <module>
    memory=args.memory, seeds=seeds, timeout=args.run_timeout,
  File "/home/angr/angr-dev/fuzzer/fuzzer/fuzzer.py", line 99, in __init__
    Fuzzer._perform_env_checks()
  File "/home/angr/angr-dev/fuzzer/fuzzer/fuzzer.py", line 599, in _perform_env_checks
    raise InstallError(err)
fuzzer.fuzzer.InstallError: AFL Warning: We probably want the fork() children to run first
execute 'echo 1 | sudo tee /proc/sys/kernel/sched_child_runs_first'

Exception ignored in: <bound method Fuzzer.__del__ of <fuzzer.fuzzer.Fuzzer object at 0x7f188ab629e8>>
Traceback (most recent call last):
  File "/home/angr/angr-dev/fuzzer/fuzzer/fuzzer.py", line 665, in __del__
    self.kill()
  File "/home/angr/angr-dev/fuzzer/fuzzer/fuzzer.py", line 266, in kill
    for p in self.procs:
2、my unsuccessful solution
I run the following cmd in docker environment which gets from shellphish/mechaphish image. It output
the above error message.I'm trying to modify the sched_child_runs_first config file. But it's readonly file that cannot be changed. How can i solve this problem? I'm very appreciated for you help.
         echo 1 | sudo tee /proc/sys/kernel/sched_child_runs_first
         tee: /proc/sys/kernel/sched_child_runs_first: Read-only file system

**Comment by xiaozhouqi** [comment]
shellphuzz -i -c 4 ./buggy
